import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=' flex flex-col gap-1 '>
          <h1>coolest app ever</h1>
          <Link className=' border border-t-neutral-50' href={"/"}>Navigate home</Link>
          <Link className=' border border-t-neutral-50' href={"/ssr"}>Navigate ssr</Link>
          <Link className=' border border-t-neutral-50' href={"/csr"}>Navigate csr</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
